defaultProject: rsr-bi-group-prd-701e
defaultLocation: us-east1 # update this when pull updated code from another region form
defaultDataset: db_nam_blue_cnsd # update this when pull updated code from another region form
defaultAssertionDataset: dataform_assertions
dataformCoreVersion: 3.0.0
# vars:
#     dfm_run_datetime: "`r format(Sys.time(), '%d %B, %Y')`"
#     dfm_name: "'dataform-blue-cnsd-nam'"
